### ISSUE TITLE
Custom Branchnamen unterstützen

### ISSUE THREAD

**Issue by Paulomart** [5minds/ci_tools#105]
## Description

Aktuell sind master/beta/develop hart festgelegt.

## Possible solution

Möglichkeit diese in einer Configdatei festzulegen

**Comment by rrrene** [comment]
@Paulomart Das kann ab `v3.3.2` mit drei Umgebungsvariablen gesteuert werden:

- `CI_TOOLS_ALPHA_BRANCH`
- `CI_TOOLS_BETA_BRANCH`
- `CI_TOOLS_STABLE_BRANCH`
