### ISSUE TITLE
Konfigurationsmöglichkeiten für Release Tags

### ISSUE THREAD

**Issue by ElRaptorus** [5minds/ci_tools#130]
## Beschreibung

Wenn ich die Main Branches (Alpha, Beta, Develop, Master) auf einen eigenen Branch mit anderem Name umstelle, bekomme ich derzeit noch Releases auf NuGet, NPM und GH, die mit "Alpha", bzw. "Beta" beschriftet sind. 

Es gibt Setups, in denen es praktischer wäre, die Namen der Tags ebenfalls anpassen zu können. 

Beispiel:
Ich stelle per `CI_TOOLS_ALPHA_BRANCH` den Branch für Alpha Releases auf "Pre" um.
Aktuell würden diese Releases noch mit "Alpha" getagged werden, obwohl hier ein "Pre" für meinen Use Case passender wäre.

**Comment by rrrene** [comment]
Wenn die CI Tools jetzt auch "Produkt" sind, dann wäre hier wichtig, dass wir die Namen von Branch, Suffix und ggf. Tag trennen und separat konfigurierbar machen. 

Der Original-Use-Case der CI Tools ist ja, dass die CI Tools als interne Tools für die interne Versionierung darauf ausgelegt sind, drei Sachen namens "Alpha", "Beta" und "Stable" zu unterscheiden. 

Wenn wir hier nun beliebige Sachen mit beliebigen Namen für beliebige Projekte unterscheiden wollen, dann sollten wir das nicht übers Knie brechen.

**Comment by rrrene** [comment]
Ob die CI Tools jetzt als Produkt wahrgenommen und mit entsprechenden Auswänden gewartet werden sollen, muss allerdings @moellenbeck entscheiden, da ich leider noch nicht verstehe, warum ich als Projektleiter in einem Kundenprojekt Alphas und Betas haben wollen würde und nicht einfach mit Versionsnummern arbeiten kann.
