### ISSUE TITLE
CI Tools brechen nicht ab, wenn npm publish 500er Fehler wirft

### ISSUE THREAD

**Issue by ElRaptorus** [5minds/ci_tools#67]
## Beschreibung

Man betrachte z.B. folgenden Build:
https://github.com/atlas-engine/AdminDomain.Core/runs/677337179?check_suite_focus=true#step:7:98

Hier ist der Build eigentlich fehlgeschlagen, da "npm publish" einen 503 Fehler geworfen hatte. Das kam daher, dass die NPM Registry down war.

Die CI Tools haben diesen Fehler jedoch nicht abgefangen und das zugehörige Command ist nicht mit einem Fehler abgebrochen.
Der Build lief daher normal weiter und wurde im Endergebnis als "erfolgreich" gekennzeichnet.

## Mögliche Lösung

Die CI Tools sollten in der Lage sein 500er Fehler abzufangen und den entsprechenden Build zu crashen.

**Comment by NullEnt1ty** [comment]
npm wird in diesem Fall normalerweise mit einem Return Code ungleich 0 beendet. Leider wird das aktuell durch unsere Abstraktionsfunktionen "sh" und "asyncSh" verschluckt.

Wir könnten die beiden Funktionen so erweitern, dass sie den Return Code in einem Objekt mit der Ausgabe zusammen zurückgeben oder wir prüfen einfach die Ausgabe auf "npm ERR".

**Comment by ElRaptorus** [comment]
Abgelöst durch #123
