### ISSUE TITLE
Add tag prefix to handle several packages in one repo 

### ISSUE THREAD

**Issue by alexanderkasten** [5minds/ci_tools#97]
## Possible solution

Es sollte ermöglicht werden über ein Argument einen Tag Prefix festzulegen, damit in einem Repo mehrere Pakate in unterschiedlicher Version veröffentlicht werden können. 
Das könnte so aussehen: 

```
ci_tools commit-and-tag-version --tag-prefix studio_
```

Dazu müsste (auf den ersten Blick) `commit-and-tag-version` und `update-github-release` angepasst werden.

**Comment by ElRaptorus** [comment]
Kann man wohl beerdigen, da wir solche Setups nicht mehr haben. 
Falls man ordnerspezifische Operationen ausführen muss, kann man besser in der Workflow File das `working-directory` Setting nutzen.
